### ISSUE TITLE
Object does not exist error without pre pulling.

### ISSUE THREAD

**Issue by bwplotka** [efficientgo/e2e#3]
Sometimes I was getting weird errors of objects does not exist for new docker images. What always worked was:

* I had to run e2e with `WithVerbose` option
* copy `docker run ... ` command for problematic image.
* Run it manually locally

After that all runs 100% works. 

Leaving here as a known issue to debug (: I suspect some permissions on my machines? 🤔 Let's see if other can repro!

**Comment by matej-g** [comment]
I've been running into this issue while trying the interactive test from https://github.com/thanos-io/thanos/pull/4573 and I think I am able to credibly reproduce it by:

1. Removing image via `docker image rm <...>`
2. Starting a test again which depends on using the removed image
3. Passing `WithVerbose` and watching it gradually downloading all layers of Docker image while seeing constant checks if the container is started yet (`dockerEnv: [docker inspect --format={{json .State.Running}} interactive-cadvisor]`)
4. Ultimately it fails with `Error: No such object: <container-name>` and `unexpected error: docker container <container-name> failed to start: exit status 1`

My suspicion is actually that there is nothing wrong with permissions or the setup _per se_, but rather the pull of a Docker image can take so long that while the checks in `waitForRunning()` are looping, the time it takes to download and start an image exceeds the default `WaitReadyBackoff` setting and the initiation sequence is terminated.
