### ISSUE TITLE
Possibility of infinite loop when waiting for missing metrics to appear

### ISSUE THREAD

**Issue by douglascamata** [efficientgo/e2e#38]
When using `InstrumentedRunnable.WaitSumMetricsWithOptions(...)` together with `e2e.WaitMissingMetrics()` it's possible that tests get stuck forever because of [this loop](https://github.com/efficientgo/e2e/blob/main/instrumented.go#L171).

It would be great to have a safety mechanism to timeout the wait. It helps avoid long running CI jobs, which can be $$$ friendly.

**Comment by matej-g** [comment]
Yes, this is a good catch, I think it would make sense to do `metricsWaitBackoff.Wait()` here as well - even if metric is missing, we should be counting this towards the total number of retries.
