### ISSUE TITLE
Dependency on tools.git/core is for a detached commit; this breaks builds

### ISSUE THREAD

**Issue by mmazur** [efficientgo/e2e#41]
https://github.com/efficientgo/e2e/blob/main/go.mod#L5-L6 says:

```
require (
	github.com/efficientgo/tools/core v0.0.0-20210129205121-421d0828c9a6
```

efficientgo/tools@421d0828c9a6 is a _commit does not belong to any branch on this repository, and may belong to a fork outside of the repository_ and it seems I'm unable to build https://github.com/observatorium/obsctl because of this:

```
go: github.com/efficientgo/e2e@v0.12.0 requires
        github.com/efficientgo/tools/core@v0.0.0-20210129205121-421d0828c9a6: invalid version: unknown revision 421d0828c9a6
make: *** [Makefile:54: deps] Błąd 1
```

Ref: thanos-io/thanos#4806

**Comment by bwplotka** [comment]
Yup, we sometimes have this issue if you have old version of tools in Go cache.

We moved this module to separate repo so now this should be resolved if we move e2e to it: https://github.com/efficientgo/core 

Doing PR now
