### ISSUE TITLE
Consider adding HTTPS readiness probe

### ISSUE THREAD

**Issue by matej-g** [efficientgo/e2e#9]
On occasions, I'm using the framework to run services which are running only on HTTPS port (thus HTTP probe won't work). In such cases I tend to do a simple command readiness check by using `curl --insecure ... https://<readiness-endpoint>` or similar command. However, this has an overhead, since I have to 1) have a utility capable of probing available inside the container; 2) need to craft my own command with arguments each time.

It could be beneficial to have a HTTPS readiness probe, on similar principle (e.g. it could skip verifying TLS, which should be fine for purely testing purposes).

**Comment by bwplotka** [comment]
Yup 👍🏽
